export interface HorarioBlockSeed {
  nivel: string;
  grado: string;
  seccion: string;
  dia: number;
  periodoOrden: number;
  cursoNombre: string;
  docenteUsername: string;
}

const b = (
  nivel: string,
  grado: string,
  seccion: string,
  dia: number,
  periodoOrden: number,
  cursoNombre: string,
  docenteUsername: string,
): HorarioBlockSeed => ({
  nivel,
  grado,
  seccion,
  dia,
  periodoOrden,
  cursoNombre,
  docenteUsername,
});

/** Cuadros semanales demo persistidos en horario_blocks. */
export const HORARIO_BLOCKS_SEED: HorarioBlockSeed[] = [
  // ── Primaria 5° A ─────────────────────────────────────────────────────
  b('Primaria', '5°', 'A', 0, 1, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 0, 2, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 0, 3, 'Comprensión Lectora', 'm.flores'),
  b('Primaria', '5°', 'A', 0, 5, 'Producción de Textos', 'm.flores'),
  b('Primaria', '5°', 'A', 0, 6, 'Ciencia y Tecnología', 'e.quispe'),
  b('Primaria', '5°', 'A', 1, 1, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 1, 2, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'A', 1, 3, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'A', 1, 5, 'Comprensión Lectora', 'm.flores'),
  b('Primaria', '5°', 'A', 1, 6, 'Arte y Cultura', 'c.lazo'),
  b('Primaria', '5°', 'A', 2, 1, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 2, 2, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 2, 3, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'A', 2, 5, 'Comprensión Lectora', 'm.flores'),
  b('Primaria', '5°', 'A', 2, 6, 'Arte y Cultura', 'c.lazo'),
  b('Primaria', '5°', 'A', 3, 1, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'A', 3, 2, 'Producción de Textos', 'm.flores'),
  b('Primaria', '5°', 'A', 3, 3, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'A', 3, 5, 'Historia del Perú', 'r.ccapa'),
  b('Primaria', '5°', 'A', 3, 6, 'Historia del Perú', 'r.ccapa'),
  b('Primaria', '5°', 'A', 4, 1, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 4, 2, 'Ed. Religiosa', 'f.calcina'),
  b('Primaria', '5°', 'A', 4, 3, 'Ciencia y Tecnología', 'e.quispe'),
  b('Primaria', '5°', 'A', 4, 5, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'A', 4, 6, 'Ciencia y Tecnología', 'e.quispe'),
  b('Primaria', '5°', 'A', 0, 8, 'Historia del Perú', 'r.ccapa'),
  b('Primaria', '5°', 'A', 1, 8, 'Historia del Perú', 'r.ccapa'),
  b('Primaria', '5°', 'A', 2, 8, 'Ciencia y Tecnología', 'e.quispe'),
  b('Primaria', '5°', 'A', 3, 8, 'Producción de Textos', 'm.flores'),
  b('Primaria', '5°', 'A', 4, 8, 'Matemática', 'docente'),
  b('Primaria', '5°', 'A', 0, 9, 'Comprensión Lectora', 'm.flores'),
  b('Primaria', '5°', 'A', 1, 9, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'A', 2, 9, 'Inglés', 'm.pauca'),

  // ── Primaria 5° B (horas desfasadas vs 5° A para docentes compartidos) ──
  b('Primaria', '5°', 'B', 0, 1, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 0, 2, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 0, 8, 'Comprensión Lectora', 'm.flores'),
  b('Primaria', '5°', 'B', 1, 1, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 1, 8, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'B', 1, 9, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'B', 2, 1, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 2, 2, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 2, 8, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'B', 3, 8, 'Inglés', 'm.pauca'),
  b('Primaria', '5°', 'B', 3, 9, 'Producción de Textos', 'm.flores'),
  b('Primaria', '5°', 'B', 3, 6, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'B', 4, 1, 'Matemática', 'r.salas'),
  b('Primaria', '5°', 'B', 4, 8, 'Educación Física', 'h.terrazas'),
  b('Primaria', '5°', 'B', 4, 9, 'Ciencia y Tecnología', 'e.quispe'),

  // ── Secundaria 3° A (docentes distintos a Primaria 5° para evitar solapamientos) ──
  b('Secundaria', '3°', 'A', 0, 1, 'Álgebra', 'juan.perez'),
  b('Secundaria', '3°', 'A', 0, 2, 'Álgebra', 'juan.perez'),
  b('Secundaria', '3°', 'A', 0, 3, 'Comunicación', 's.benavides'),
  b('Secundaria', '3°', 'A', 0, 5, 'Biología', 'e.quispe'),
  b('Secundaria', '3°', 'A', 0, 10, 'Biología', 'e.quispe'),
  b('Secundaria', '3°', 'A', 0, 7, 'Historia del Perú', 'd.vela'),
  b('Secundaria', '3°', 'A', 0, 8, 'Historia del Perú', 'd.vela'),
  b('Secundaria', '3°', 'A', 1, 1, 'Álgebra', 'juan.perez'),
  b('Secundaria', '3°', 'A', 1, 2, 'Geometría', 'r.salas'),
  b('Secundaria', '3°', 'A', 1, 3, 'Comunicación', 's.benavides'),
  b('Secundaria', '3°', 'A', 1, 5, 'Biología', 'e.quispe'),
  b('Secundaria', '3°', 'A', 1, 6, 'Geografía', 'r.salas'),
  b('Secundaria', '3°', 'A', 1, 7, 'Arte y Cultura', 'c.lazo'),
  b('Secundaria', '3°', 'A', 1, 8, 'Arte y Cultura', 'c.lazo'),
  b('Secundaria', '3°', 'A', 2, 1, 'Álgebra', 'juan.perez'),
  b('Secundaria', '3°', 'A', 2, 2, 'Geometría', 'r.salas'),
  b('Secundaria', '3°', 'A', 2, 3, 'Comunicación', 's.benavides'),
  b('Secundaria', '3°', 'A', 2, 5, 'Inglés', 'e.cordova'),
  b('Secundaria', '3°', 'A', 2, 10, 'Educación Física', 'h.terrazas'),
  b('Secundaria', '3°', 'A', 4, 7, 'Educación Física', 'h.terrazas'),
  b('Secundaria', '3°', 'A', 3, 1, 'Comunicación', 's.benavides'),
  b('Secundaria', '3°', 'A', 3, 2, 'Inglés', 'e.cordova'),
  b('Secundaria', '3°', 'A', 3, 3, 'DPCC', 'f.calcina'),
  b('Secundaria', '3°', 'A', 3, 5, 'Inglés', 'e.cordova'),
  b('Secundaria', '3°', 'A', 3, 6, 'Geografía', 'r.salas'),
  b('Secundaria', '3°', 'A', 3, 7, 'Educación Física', 'h.terrazas'),
  b('Secundaria', '3°', 'A', 4, 1, 'DPCC', 'f.calcina'),
  b('Secundaria', '3°', 'A', 0, 9, 'Geometría', 'r.salas'),
  b('Secundaria', '3°', 'A', 4, 9, 'Educación Física', 'h.terrazas'),
  b('Secundaria', '3°', 'A', 2, 9, 'Historia del Perú', 'd.vela'),
  b('Secundaria', '3°', 'A', 3, 9, 'Biología', 'e.quispe'),
  b('Secundaria', '3°', 'A', 4, 8, 'Física', 'o.nunez'),
  b('Secundaria', '3°', 'A', 0, 10, 'Comunicación', 's.benavides'),
  b('Secundaria', '3°', 'A', 1, 10, 'Inglés', 'e.cordova'),
  b('Secundaria', '3°', 'A', 2, 10, 'Educación Física', 'h.terrazas'),
];
