import type {
  CurriculumEstado,
  CurriculumTipoEscala,
  CurriculumTipoPeriodo,
} from './entities/curriculum.entity';

const G_INI = ['3 años', '4 años', '5 años'];
const G_PRI = ['1°', '2°', '3°', '4°', '5°', '6°'];
const G_SEC = ['1°', '2°', '3°', '4°', '5°'];

export const CURRICULA_SEED_DATA = {
  curriculas: [
    { anio: 2026, nivel: 'Inicial', estado: 'activo' as CurriculumEstado, version: '1.0', tipoEscala: 'competencia' as CurriculumTipoEscala, tipoPeriodo: 'bimestral' as CurriculumTipoPeriodo, fechaCreacion: '2026-01-10' },
    { anio: 2026, nivel: 'Primaria', estado: 'activo' as CurriculumEstado, version: '1.0', tipoEscala: 'numerica' as CurriculumTipoEscala, tipoPeriodo: 'bimestral' as CurriculumTipoPeriodo, fechaCreacion: '2026-01-10' },
    { anio: 2026, nivel: 'Secundaria', estado: 'activo' as CurriculumEstado, version: '1.1', tipoEscala: 'numerica' as CurriculumTipoEscala, tipoPeriodo: 'bimestral' as CurriculumTipoPeriodo, fechaCreacion: '2026-01-10' },
    { anio: 2025, nivel: 'Primaria', estado: 'inactivo' as CurriculumEstado, version: '1.0', tipoEscala: 'numerica' as CurriculumTipoEscala, tipoPeriodo: 'trimestral' as CurriculumTipoPeriodo, fechaCreacion: '2025-01-08' },
    { anio: 2025, nivel: 'Secundaria', estado: 'inactivo' as CurriculumEstado, version: '1.0', tipoEscala: 'numerica' as CurriculumTipoEscala, tipoPeriodo: 'trimestral' as CurriculumTipoPeriodo, fechaCreacion: '2025-01-08' },
    { anio: 2026, nivel: 'Inicial', estado: 'borrador' as CurriculumEstado, version: '2.0', tipoEscala: 'competencia' as CurriculumTipoEscala, tipoPeriodo: 'bimestral' as CurriculumTipoPeriodo, fechaCreacion: '2026-03-15' },
  ],
  areas: [
    { nombre: 'Comunicación', nivel: 'Inicial', orden: 1, colorClass: 'bg-blue-50 border-blue-200 text-blue-800', dotClass: 'bg-blue-500' },
    { nombre: 'Matemática', nivel: 'Inicial', orden: 2, colorClass: 'bg-indigo-50 border-indigo-200 text-indigo-800', dotClass: 'bg-indigo-500' },
    { nombre: 'Personal Social', nivel: 'Inicial', orden: 3, colorClass: 'bg-green-50 border-green-200 text-green-800', dotClass: 'bg-green-500' },
    { nombre: 'Ciencia y Tecnología', nivel: 'Inicial', orden: 4, colorClass: 'bg-yellow-50 border-yellow-200 text-yellow-800', dotClass: 'bg-yellow-500' },
    { nombre: 'Arte y Cultura', nivel: 'Inicial', orden: 5, colorClass: 'bg-pink-50 border-pink-200 text-pink-800', dotClass: 'bg-pink-500' },
    { nombre: 'Psicomotricidad', nivel: 'Inicial', orden: 6, colorClass: 'bg-orange-50 border-orange-200 text-orange-800', dotClass: 'bg-orange-500' },
    { nombre: 'Matemática', nivel: 'Primaria', orden: 1, colorClass: 'bg-indigo-50 border-indigo-200 text-indigo-800', dotClass: 'bg-indigo-500' },
    { nombre: 'Comunicación', nivel: 'Primaria', orden: 2, colorClass: 'bg-blue-50 border-blue-200 text-blue-800', dotClass: 'bg-blue-500' },
    { nombre: 'Ciencia y Tecnología', nivel: 'Primaria', orden: 3, colorClass: 'bg-emerald-50 border-emerald-200 text-emerald-800', dotClass: 'bg-emerald-500' },
    { nombre: 'Ciencias Sociales', nivel: 'Primaria', orden: 4, colorClass: 'bg-amber-50 border-amber-200 text-amber-800', dotClass: 'bg-amber-500' },
    { nombre: 'Arte y Cultura', nivel: 'Primaria', orden: 5, colorClass: 'bg-pink-50 border-pink-200 text-pink-800', dotClass: 'bg-pink-500' },
    { nombre: 'Educación Física', nivel: 'Primaria', orden: 6, colorClass: 'bg-lime-50 border-lime-200 text-lime-800', dotClass: 'bg-lime-500' },
    { nombre: 'Personal Social', nivel: 'Primaria', orden: 7, colorClass: 'bg-green-50 border-green-200 text-green-800', dotClass: 'bg-green-500' },
    { nombre: 'Inglés', nivel: 'Primaria', orden: 8, colorClass: 'bg-sky-50 border-sky-200 text-sky-800', dotClass: 'bg-sky-500' },
    { nombre: 'Ed. Religiosa', nivel: 'Primaria', orden: 9, colorClass: 'bg-violet-50 border-violet-200 text-violet-800', dotClass: 'bg-violet-500' },
    { nombre: 'Matemática', nivel: 'Secundaria', orden: 1, colorClass: 'bg-indigo-50 border-indigo-200 text-indigo-800', dotClass: 'bg-indigo-500' },
    { nombre: 'Comunicación', nivel: 'Secundaria', orden: 2, colorClass: 'bg-blue-50 border-blue-200 text-blue-800', dotClass: 'bg-blue-500' },
    { nombre: 'Ciencia y Tecnología', nivel: 'Secundaria', orden: 3, colorClass: 'bg-emerald-50 border-emerald-200 text-emerald-800', dotClass: 'bg-emerald-500' },
    { nombre: 'CCSS e Historia', nivel: 'Secundaria', orden: 4, colorClass: 'bg-amber-50 border-amber-200 text-amber-800', dotClass: 'bg-amber-500' },
    { nombre: 'Inglés', nivel: 'Secundaria', orden: 5, colorClass: 'bg-sky-50 border-sky-200 text-sky-800', dotClass: 'bg-sky-500' },
    { nombre: 'DPCC', nivel: 'Secundaria', orden: 6, colorClass: 'bg-teal-50 border-teal-200 text-teal-800', dotClass: 'bg-teal-500' },
    { nombre: 'Arte y Cultura', nivel: 'Secundaria', orden: 7, colorClass: 'bg-pink-50 border-pink-200 text-pink-800', dotClass: 'bg-pink-500' },
    { nombre: 'Educación Física', nivel: 'Secundaria', orden: 8, colorClass: 'bg-lime-50 border-lime-200 text-lime-800', dotClass: 'bg-lime-500' },
    { nombre: 'Ed. para el Trabajo', nivel: 'Secundaria', orden: 9, colorClass: 'bg-orange-50 border-orange-200 text-orange-800', dotClass: 'bg-orange-500' },
  ],
  subjects: [
    { areaIndex: 0, nombre: 'Comunicación', nivel: 'Inicial', grados: G_INI, horasSemanales: 5 },
    { areaIndex: 1, nombre: 'Matemática', nivel: 'Inicial', grados: G_INI, horasSemanales: 4 },
    { areaIndex: 2, nombre: 'Personal Social', nivel: 'Inicial', grados: G_INI, horasSemanales: 3 },
    { areaIndex: 3, nombre: 'Ciencia y Tecnología', nivel: 'Inicial', grados: G_INI, horasSemanales: 3 },
    { areaIndex: 4, nombre: 'Arte y Cultura', nivel: 'Inicial', grados: G_INI, horasSemanales: 2 },
    { areaIndex: 5, nombre: 'Psicomotricidad', nivel: 'Inicial', grados: G_INI, horasSemanales: 3 },
    { areaIndex: 6, nombre: 'Matemática', nivel: 'Primaria', grados: G_PRI, horasSemanales: 6 },
    { areaIndex: 7, nombre: 'Comprensión Lectora', nivel: 'Primaria', grados: G_PRI, horasSemanales: 3 },
    { areaIndex: 7, nombre: 'Producción de Textos', nivel: 'Primaria', grados: G_PRI, horasSemanales: 2 },
    { areaIndex: 8, nombre: 'Ciencia y Tecnología', nivel: 'Primaria', grados: G_PRI, horasSemanales: 3 },
    { areaIndex: 9, nombre: 'Historia del Perú', nivel: 'Primaria', grados: ['4°', '5°', '6°'], horasSemanales: 2 },
    { areaIndex: 9, nombre: 'Geografía', nivel: 'Primaria', grados: ['4°', '5°', '6°'], horasSemanales: 1 },
    { areaIndex: 10, nombre: 'Arte y Cultura', nivel: 'Primaria', grados: G_PRI, horasSemanales: 2 },
    { areaIndex: 11, nombre: 'Educación Física', nivel: 'Primaria', grados: G_PRI, horasSemanales: 3 },
    { areaIndex: 12, nombre: 'Personal Social', nivel: 'Primaria', grados: ['1°', '2°', '3°'], horasSemanales: 2 },
    { areaIndex: 13, nombre: 'Inglés', nivel: 'Primaria', grados: G_PRI, horasSemanales: 3 },
    { areaIndex: 14, nombre: 'Ed. Religiosa', nivel: 'Primaria', grados: G_PRI, horasSemanales: 1 },
    { areaIndex: 15, nombre: 'Álgebra', nivel: 'Secundaria', grados: ['1°', '2°', '3°'], horasSemanales: 4 },
    { areaIndex: 15, nombre: 'Geometría', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 2 },
    { areaIndex: 15, nombre: 'Trigonometría', nivel: 'Secundaria', grados: ['4°', '5°'], horasSemanales: 3 },
    { areaIndex: 15, nombre: 'Aritmética', nivel: 'Secundaria', grados: ['1°', '2°'], horasSemanales: 2 },
    { areaIndex: 16, nombre: 'Comunicación', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 4 },
    { areaIndex: 17, nombre: 'Física', nivel: 'Secundaria', grados: ['3°', '4°', '5°'], horasSemanales: 3 },
    { areaIndex: 17, nombre: 'Química', nivel: 'Secundaria', grados: ['3°', '4°', '5°'], horasSemanales: 2 },
    { areaIndex: 17, nombre: 'Biología', nivel: 'Secundaria', grados: ['1°', '2°', '3°'], horasSemanales: 3 },
    { areaIndex: 17, nombre: 'CTA', nivel: 'Secundaria', grados: ['1°', '2°'], horasSemanales: 4 },
    { areaIndex: 18, nombre: 'Historia del Perú', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 2 },
    { areaIndex: 18, nombre: 'Historia Universal', nivel: 'Secundaria', grados: ['3°', '4°', '5°'], horasSemanales: 2 },
    { areaIndex: 18, nombre: 'Geografía', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 2 },
    { areaIndex: 19, nombre: 'Inglés', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 3 },
    { areaIndex: 20, nombre: 'DPCC', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 2 },
    { areaIndex: 21, nombre: 'Arte y Cultura', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 2 },
    { areaIndex: 22, nombre: 'Educación Física', nivel: 'Secundaria', grados: G_SEC, horasSemanales: 3 },
    { areaIndex: 23, nombre: 'Ed. para el Trabajo', nivel: 'Secundaria', grados: ['3°', '4°', '5°'], horasSemanales: 3 },
  ],
  assignments: [
    { docenteNombre: 'Juan Pérez García', subjectIndex: 6, nivel: 'Primaria', grado: '5°', secciones: ['A', 'B'] },
    { docenteNombre: 'Juan Pérez García', subjectIndex: 6, nivel: 'Primaria', grado: '6°', secciones: ['A'] },
    { docenteNombre: 'Roberto Quispe Tapia', subjectIndex: 6, nivel: 'Primaria', grado: '4°', secciones: ['A', 'B'] },
    { docenteNombre: 'Rosa Mendoza Lima', subjectIndex: 7, nivel: 'Primaria', grado: '5°', secciones: ['A', 'B'] },
    { docenteNombre: 'Rosa Mendoza Lima', subjectIndex: 8, nivel: 'Primaria', grado: '5°', secciones: ['A', 'B'] },
    { docenteNombre: 'Roberto Quispe Tapia', subjectIndex: 18, nivel: 'Secundaria', grado: '3°', secciones: ['A', 'B', 'C'] },
    { docenteNombre: 'Carlos Torres Vega', subjectIndex: 26, nivel: 'Secundaria', grado: '2°', secciones: ['A', 'B'] },
    { docenteNombre: 'María López Castro', subjectIndex: 28, nivel: 'Secundaria', grado: '3°', secciones: ['A', 'B', 'C'] },
    { docenteNombre: 'Pedro Sánchez Ruiz', subjectIndex: 30, nivel: 'Secundaria', grado: '4°', secciones: ['A', 'B'] },
    { docenteNombre: 'Ana Flores Díaz', subjectIndex: 13, nivel: 'Primaria', grado: '4°', secciones: ['A', 'B'] },
    { docenteNombre: 'Luis Vargas Mora', subjectIndex: 12, nivel: 'Primaria', grado: '5°', secciones: ['A', 'B'] },
    { docenteNombre: 'Elena García Paz', subjectIndex: 16, nivel: 'Primaria', grado: '6°', secciones: ['A'] },
  ],
};
